routes/web.php
<?php

use App\Exports\ClientsExport;
use App\Exports\TransactionsExport;
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\Auth\ProfileController;
use App\Http\Controllers\Backend\AgentController;
use App\Http\Controllers\Backend\CampagneController;
use App\Http\Controllers\Backend\ClientController;
use App\Http\Controllers\Backend\CommerceController;
use App\Http\Controllers\Backend\CustomCashbackController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\Localisation\PaysController;
use App\Http\Controllers\Backend\Localisation\QuartiersController;
use App\Http\Controllers\Backend\Localisation\VillesController;
use App\Http\Controllers\Backend\PackageController;
use App\Http\Controllers\Backend\PermissionController;
use App\Http\Controllers\Backend\PointVenteController;
use App\Http\Controllers\Backend\ProgrammeController;
use App\Http\Controllers\Backend\RoleController;
use App\Http\Controllers\Backend\TransactionController;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\Backend\VendeurController;
use App\Http\Controllers\Backend\WalletController;
use App\Http\Controllers\CaptchaValidationController;
use App\Http\Controllers\FraudController;
use App\Http\Controllers\ParametrageController;
use App\Http\Controllers\QRCodeController;
use App\Http\Controllers\TicketController;

// Delivery
use App\Http\Controllers\Backend\Delivery\CompanyController;
use App\Http\Controllers\Backend\Delivery\DeliverController;
use App\Http\Controllers\Backend\Delivery\DeliveryController;
use App\Http\Controllers\Backend\Delivery\OrderController;
use App\Http\Controllers\Backend\Delivery\PaymentMethodController;
use App\Http\Controllers\Backend\Delivery\SubscriptionController;
use App\Http\Controllers\Backend\Delivery\DeliveryTransactionController;

// Marketplace
use App\Http\Controllers\Backend\Marketplace\MarketplaceCategoryController;
use App\Http\Controllers\Backend\Marketplace\MarketplaceProductCategoryController;
use App\Http\Controllers\Backend\Marketplace\MarketplaceShopController;
use App\Http\Controllers\Backend\Marketplace\MarketplaceShopSubcategoryController;

use App\Http\Controllers\Backend\Marketplace\MarketplaceArticleController;
use App\Http\Controllers\Backend\Marketplace\MarketplaceOrderController;
use App\Http\Controllers\Backend\Marketplace\MarketplaceCustomerController;
use App\Http\Controllers\Backend\Marketplace\MarketplacePaymentController;
use App\Http\Controllers\Backend\Marketplace\MarketplacePeriodicityWithdrawalController;
use App\Http\Controllers\Backend\Marketplace\MarketplaceAddonController;
use App\Http\Controllers\Backend\Marketplace\MarketplaceNoteController;
use App\Http\Controllers\Backend\Marketplace\MarketplaceSubscriptionController;
use App\Http\Controllers\Backend\Marketplace\MarketplaceTransactionController;
use App\Http\Controllers\Backend\PaymentServiceProvider\PaymentServiceProviderController;


use Illuminate\Support\Facades\Route;


Route::domain(config('app.env') != 'production' ? 'download-dev.koree.africa' : 'download.koree.africa')->group(function () {
    Route::get('/', [QRCodeController::class, 'frontend']);
});

Route::domain(config('app.env') != 'production' ? 'store-dev.koree.africa' : 'store.koree.africa')->group(function () {
    Route::get('/', [QRCodeController::class, 'frontend']);
});

Route::get('/qrcodes',[QRCodeController::class, 'frontend']);



Route::get('/', function () {
    return view('frontend/index');
});

Route::get('/politique-confidentialite', function () {
    return view('frontend/politique');
})->name('politique');


Route::get('/mentions-legales', function () {
    return view('frontend/mentions_legales');
})->name('mention-legale');

Route::get('logout', [AuthController::class, 'logout']);
Route::get('contact-form-captcha', [CaptchaValidationController::class, 'index']);
Route::post('captcha-validation', [CaptchaValidationController::class, 'capthcaFormValidate']);
Route::get('reload-captcha', [CaptchaValidationController::class, 'reloadCaptcha']);


//Route::get('/confirm-password', function () {
//    return view('auth.confirm-password');
//})->middleware('auth')->name('password.confirm');

//Route::post('/confirm-password', function (Request $request) {
//    if (! Hash::check($request->password, $request->user()->password)) {
//        return back()->withErrors([
//            'password' => ['The provided password does not match our records.']
//        ]);
//    }
//
//    $request->session()->passwordConfirmed();
//
//    return redirect()->intended();
//})->middleware(['auth', 'throttle:6,1']);

Route::group(['middleware' => ['auth']], function () {

    // route for intern users
    Route::get('users/waitinglist', [UserController::class, 'listUsersOnWaitinglist'])->name('users-on-waitinglist');
    Route::get('users/users-internes', [UserController::class, 'listUsersInternes'])->name('users-in');
    Route::get('users/users-internes/create', [UserController::class, 'createUsersInternes'])->name('users-in-create');
    Route::post('users/users-internes', [UserController::class, 'storeUsersInternes'])->name('users-in-store');
    Route::get('users/users-internes/{id}/edit', [UserController::class, 'editUsersInternes'])->name('users-in-edit');
    Route::put('users/users-internes/{id}', [UserController::class, 'updateUsersInternes'])->name('users-in-update');
    Route::get('users/users-internes/{id}', [UserController::class, 'showUsersInternes'])->name('users-in-show');
    Route::delete('users/users-internes/{id}', [UserController::class, 'destroyUsersInternes'])->name('users-in-destroy');

    // route for vendeurs
    Route::get('users/influenceurs', [UserController::class, 'listInfluenceurs'])->name('users.influenceurs.index');
    Route::get('users/vendeurs', [UserController::class, 'listVendeurs'])->name('vendeurs-in');
    Route::get('users/vendeurss/create', [UserController::class, 'createVendeurs'])->name('vendeurs-in-create');
    Route::post('users/vendeurs', [UserController::class, 'storeVendeurs'])->name('vendeurs-in-store');
    Route::get('users/vendeurs/{id}/edit', [UserController::class, 'editVendeurs'])->name('vendeurs-in-edit');
    Route::put('users/vendeurs/{id}', [UserController::class, 'updateVendeurs'])->name('vendeurs-in-update');
    Route::get('users/vendeurs/{id}', [UserController::class, 'showVendeurs'])->name('vendeurs-in-show');
    Route::delete('users/vendeurs/{id}', [UserController::class, 'destroyVendeurs'])->name('vendeurs-in-destroy');

    Route::resource('vendeurs', VendeurController::class);

    Route::get('/clients/export', ClientsExport::class)->name('clients.export');
    Route::put('clients/change-statut/{id}', [ClientController::class, 'changeStatut'])->name('client-change');
    Route::get('clients/toggle-statut/{id}', [ClientController::class, 'toggleStatut'])->name('toggle-status');
    Route::get('clients/toggle-influencer/{id}', [ClientController::class, 'toggleInfluencer'])->name('toggle-influencer');
    Route::get('/clients/mvmt/{id}', [ClientController::class, 'mvmt'])->name('clients.mvmt');
    Route::match(['GET', 'POST'],'clients/ajaxDatable', [ClientController::class, 'datatable'])->name('listing-clients-datable');
    Route::get('clients/deletion-requests', [ClientController::class, 'deletionRequests'])->name('client-deletion-requests');
    Route::get('clients/deletion-requests/accept/{id}', [ClientController::class, 'acceptDeletionRequests'])->name('client-deletion-requests-accept');
    Route::get('clients/deletion-requests/cancel/{id}', [ClientController::class, 'cancelDeletionRequests'])->name('client-deletion-requests-cancel');
    Route::get('commerces/deletion-requests/reset/{id}', [ClientController::class, 'resetDeletionRequests'])->name('client-deletion-requests-reset');
    Route::resource('clients', ClientController::class);

    Route::get('liste-parrainage', [UserController::class, 'listParrainage'])->name('listing-parrainage');
    Route::get('liste-parrainage-commerce', [UserController::class, 'listParrainageCommerce'])->name('listing-parrainage-commerce');
    Route::get('liste-transactions', [TransactionController::class, 'listeTransactions'])->name('listing-transactions');
    Route::get('liste-transactions-supprimer', [TransactionController::class, 'listeTransactionsSupprimes'])->name('listing-transactions-supprimes');
    // TODO: Start By Romuald
    Route::post('liste-transactions/ajaxDatable', [TransactionController::class, 'listeTransactionsDatatable'])->name('listing-transactions-datable');
//    Route::get('liste-transactions/export', [TransactionController::class, 'listeTransactionsExport'])->name('listing-transactions-export');
    Route::get('liste-transactions/export', TransactionsExport::class)->name('transactions.export');
    Route::get('ajaxSelect2/clients', [ClientController::class, 'listeClientsSelect2'])->name('listing-clients-select2');
    Route::get('ajaxSelect2/commerces', [CommerceController::class, 'listeCommercesSelect2'])->name('listing-commerces-select2');
    // TODO: end By Romuald
    Route::get('liste-revenu', [TransactionController::class, 'listeRevenus'])->name('listing-revenu');

    Route::get('revert_transaction_init/{id}', [TransactionController::class, 'revertInit'])->middleware(['password.confirm'])->name('transaction.revert.init');
    Route::get('revert_transaction/{id}', [TransactionController::class, 'revert'])->middleware(['password.confirm'])->name('transaction.revert');
    Route::get('restore_transaction/{id}', [TransactionController::class, 'restore'])->middleware(['password.confirm'])->name('transaction.restore');
    Route::get('restore_transaction_init/{id}', [TransactionController::class, 'restoreInit'])->middleware(['password.confirm'])->name('transaction.restore.init');
    Route::post('revert_transaction', [TransactionController::class, 'performRevert'])->name('perform.transaction.revert');

app/Http/Controllers/Backend/AgentController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Agent;
use App\Models\Commerce;
use App\Models\PointVente;
use App\Repositories\Backend\V1\AgentRepository;
use App\Repositories\Backend\V1\CommerceRepository;
use App\Repositories\Backend\V1\PointVenteRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Log;

class AgentController extends Controller
{
    protected $rpCommerce;
    protected $rpPointvente;
    protected $rpAgent;

    /**
     * create a new instance of the class
     *
     * @return void
     */
    function __construct(CommerceRepository $rpCom, PointVenteRepository $pv, AgentRepository $ag)
    {
        $this->middleware('permission:role-list|role-create|role-edit|role-delete', ['only' => ['index', 'store']]);
        $this->middleware('permission:role-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:role-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:role-delete', ['only' => ['destroy']]);

        $this->rpCommerce = $rpCom;
        $this->rpPointvente = $pv;
        $this->rpAgent = $ag;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = $this->rpAgent->getAll();
        return view('backend.agents.index', compact('data'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $commerces = Commerce::get();

        return view('backend.agents.create', compact('commerces'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'nom_prenom' => 'required',
            'point_vente_id' => 'required|numeric',
            'code' => 'required',
            'is_admin' => 'required|in:non,oui',
        ], [
            'required' => 'Le champ :attribute est obligatoire.',
            'numeric' => 'Le champ :attribute doit être numérique.',
            'digits' => 'Le champ :attribute doit etre de :digits caracteres.',
            'is_admin.in' => 'Le champ :attribute doit avoir soit la valeur oui soit la valeur non',
        ]);
        $inputs = $request->all();
        //dd(strlen($request['code']));
        if ($validator->fails()) {
            $mes = "";
            $errors = $validator->errors();
            foreach ($errors->all() as $er) {
                $mes .= $er . ' ';
            }
            return redirect()->back()->withInput($request->input())->with('error', $mes);
        } else {
            if (strlen($inputs['code']) != 5) {
                return redirect()->back()->withInput($request->input())->with('error', 'Le code doit être de 5 caractères');
            }
        }
        try{
            if($this->rpAgent->checkExistCode($inputs['code'])) {
                $mes = "Impossible d'utiliser le même code pour plusieurs agents";
                return redirect()->back()->withInput($request->input())->with('error', $mes);
            }
        }catch(\Exception $e){
            $mes = "Une erreur est survenue lors de la vérificaion du code de l'agent";
            Log::info("Une erreur c'est produite ".$e);
            return redirect()->back()->withInput($request->input())->with('error', $mes);
        }

        $desc = (isset($request['code'])) ? $request['code'] : '';
        try {
            Agent::create([
                'code' => $desc,
                'nom_prenom' => $inputs['nom_prenom'],
                'point_vente_id' => $inputs['point_vente_id'],
                'is_admin' => $inputs['is_admin'] == 'oui'
            ]);
    
            return redirect()->route('agents.index')
                ->with('success', 'Agent créé avec succès.');
        }catch(\Exception $e){
            $mes = "Une erreur est survenue lors de la créaion de l'agent";
            Log::info("Une erreur c'est produite ".$e);
            return redirect()->back()->withInput($request->input())->with('error', $mes);
        }
        
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = $this->rpAgent->getById($id);
        return view('backend.agents.show', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = $this->rpAgent->getById($id);
        $le_point_vente = PointVente::where('id', '=', $data->point_vente_id)->with('commerce')->first();
        $point_vente_id = $le_point_vente->id;
        $commerce_id = (isset($le_point_vente->commerce)) ? $le_point_vente->commerce->id : null;
        $pointventes = PointVente::where('commerce_id', '=', $commerce_id)->get();
        $commerces = Commerce::get();

        return view('backend.agents.edit', compact('data', 'commerce_id', 'point_vente_id', 'commerces', 'pointventes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'nom_prenom' => 'required',
            'point_vente_id' => 'required|numeric',
            'code' => 'required',
            'is_admin' => 'required|in:non,oui',
        ], [
            'required' => 'Le champ :attribute est obligatoire.',
            'numeric' => 'Le champ :attribute doit être numérique.',
            'digits' => 'Le champ :attribute doit etre de :digits caracteres.',
            'is_admin.in' => 'Le champ :attribute doit avoir soit la valeur oui soit la valeur non',
        ]);

        $inputs = $request->all();

        if ($validator->fails()) {
            $mes = "";
            $errors = $validator->errors();
            foreach ($errors->all() as $er) {
                $mes .= $er . ' ';
            }
            return redirect()->back()->with('error', $mes);
        } else {
            if (strlen($inputs['code']) != 5) {
                return redirect()->back()->withInput($request->input())->with('error', 'Le code doit être de 5 caractères');
            }
        }

        $data = Agent::find($id);
        $data->nom_prenom = $request->input('nom_prenom');
        $data->code = $request->input('code');
        $data->point_vente_id = $request->input('point_vente_id');
        $data->is_admin = $request->get('is_admin') == "oui";
        $data->save();

        return redirect()->route('agents.index')
            ->with('success', 'Agent mis à jour avec succès.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Agent::find($id)->delete();
        return redirect()->route('agents.index')
            ->with('success', 'Agent supprimé');
    }
}

app/Http/Controllers/Backend/Marketplace/MarketplaceAddonController.php
<?php

namespace App\Http\Controllers\Backend\Marketplace;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class MarketplaceAddonController extends Controller
{
    //
}

resources/views/backend/vendeurs/create.blade.php
@extends('layouts.main')
@section('content')
    <div class="container">
        <div class="justify-content-center">
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <strong>Opps!</strong> Erreurs signalées.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="card card-custom gutter-b example example-compact">
                <div class="card-header">
                    <h3 class="card-title">Création d'un nouveau Propriétaire</h3>
                    <div class="card-toolbar">
                        <a href="{{ route('vendeurs.index') }}" class="btn btn-success btn-sm font-weight-bold">
                            <i class="flaticon2-crisp-icons"></i>Retour à la liste</a>
                    </div>
                </div>
                <!--begin::Form-->
                {!! Form::open(array('route' => 'vendeurs.store','method'=>'POST', 'files' => true)) !!}
                    <div class="card-body">
                        <div class="form-group row">
                            <div class="col-lg-6">
                                <label>Nom(s) <span class="text-danger">*</span></label>
                                {!! Form::text('nom', null, array('placeholder' => 'Nom','class' => 'form-control', 'required'=>'required')) !!}

                            </div>
                            <div class="col-lg-6">
                                <label>Pays<span class="text-danger">*</span></label>
                                <select class="form-control" id="country_id"  name="country_id" required>
                                    @foreach($pays as $p)
                                        <option value="{{ $p->id }}">{{ $p->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-lg-6">
                                <label>Région <span class="text-danger">*</span></label>
                                <select class="form-control" id="state_id" name="state_id" required>
                                </select>
                            </div>
                            <div class="col-lg-6">
                                <label>Ville<span class="text-danger">*</span></label>
                                <select class="form-control" id="city_id" name="city_id" required>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-lg-4">
                                <label>Email  </label>
                                {!! Form::text('email', null, array('placeholder' => 'Nom','class' => 'form-control')) !!}

                            </div>
                            <div class="col-lg-4">
                                <label>Téléphone  <span class="text-danger">*</span></label>
                                {!! Form::number('telephone', null, array('placeholder' => 'Nom','class' => 'form-control', 'required'=>'required')) !!}
                            </div>
                            <div class="col-lg-4">
                                <label>Code transaction  <span class="text-danger">*</span></label>
                                {!! Form::number('code_transaction', null, array('placeholder' => 'Code transaction ','class' => 'form-control', 'required'=>'required')) !!}
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-lg-6">
                                <label>RCCM  </label>
                                {!! Form::text('rccm', null, array('placeholder' => 'Contact','class' => 'form-control')) !!}
                            </div>
                            <div class="col-lg-6">
                                <label>Adresse</label>
                                {!! Form::textArea('adresse', null, array('placeholder' => 'Adresse','rows'=>'3', 'class' => 'form-control')) !!}
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-lg-6">
                                <label>Tel fixe  </label>
                                {!! Form::text('tel_fixe', null, array('placeholder' => 'telephone fixe','class' => 'form-control')) !!}
                            </div>
                            <div class="col-lg-6">
                                <label>Contact</label>
                                {!! Form::text('contact_compte', null, array('placeholder' => 'contact', 'class' => 'form-control')) !!}
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-lg-6">
                                <label>Fonction </label>
                                {!! Form::text('fonction', null, array('placeholder' => 'Fonction','class' => 'form-control')) !!}
                            </div>
                            <div class="col-lg-6">
                                <label>Code de sécurité<span class="text-danger">*</span></label>
                                {!! Form::number('password', null, array('placeholder' => 'Code de sécurité', 'class' => 'form-control')) !!}
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Enregistrer</button>
                    </div>
            {!! Form::close() !!}
                <!--end::Form-->
            </div>

        </div>
    </div>
@endsection

@section('end_javascript')
    <script>
        $(document).ready(function(){
            $('#country_id').on('change', function(){
                var PaysID = $(this).val();
                if(PaysID){
                    $.ajax({
                        url:'/getRegion/'+PaysID,
                        type: "GET",
                        data: {"_token":"{{ csrf_token() }}"},
                        dataType: "json",
                        success: function(data){
                            if(data){
                                $('#state_id').empty(); $('#city_id').empty();
                                $('#state_id').append('<option hidden>Choisir une region</option>');
                                $.each(data, function(key, vale){
                                    $('select[name="state_id"]').append('<option value="'+ vale.id+'">'+vale.name+'</option>');
                                });
                            }else{
                                $('#state_id').empty(); $('#city_id').empty();
                            }
                        }
                    });
                }
            });
            $('#state_id').on('change', function(){
                var RegionID = $(this).val();
                if(RegionID){
                    $.ajax({
                        url:'/getVille/'+RegionID,
                        type: "GET",
                        data: {"_token":"{{ csrf_token() }}"},
                        dataType: "json",
                        success: function(data){
                            if(data){
                                $('#city_id').empty();
                                $('#city_id').append('<option hidden>Choisir une ville</option>');
                                $.each(data, function(key, vale){
                                    $('select[name="city_id"]').append('<option value="'+ vale.id+'">'+vale.name+'</option>');
                                });
                            }else{
                                $('#city_id').empty();
                            }
                        }
                    });
                }
            });
        }); // fin doc ready

    </script>
@endsection

resources/views/backend/vendeurs/index.blade.php
@extends('layouts.main')
@section('content')
    <!--begin::Card-->
    <div class="card card-custom gutter-b">
        <div class="card-header flex-wrap border-0 pt-6 pb-0">
            <div class="card-title">
                <h3 class="card-label">Liste des propriétaires de commerce
                    <span class="d-block text-muted pt-2 font-size-sm">pour tous les pays</span></h3>
            </div>
            <div class="card-toolbar">
                <!--begin::Button-->
                @can('commerce-create')
                <a href="{{ route('vendeurs.create') }}" class="btn btn-primary font-weight-bolder">
                    <i class="flaticon2-add-square icon-md"></i>Nouveau Propriétaire
                </a>
                @endcan
                <!--end::Button-->
            </div>
        </div>
        <div class="card-body">
            <!--begin: Datatable-->
            <table class="table table-separate table-head-custom table-checkable" id="kt_datatable1">
                <thead>
                <tr>
                    <th>Nom</th>
                    <th>Adresse</th>
                    <th>Telephone</th>
                    <th>Code de transaction</th>
                    <th>RCCM</th>
                    <th>Ville</th>
                    <th>Pays</th>
                    <th>Créé le</th>
                    <th width="180px">Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach ($data as $key => $p)
                    <tr>
                        <td>{{ $p->nom }}</td>
                        <td>{{ wordwrap($p->adresse) }}</td>
                        <td>{{ $p->user->telephone }}</td>
                        <td>{{ $p->code_transaction ?? ''}}</td>
                        <td>{{ $p->rccm ?? '' }}</td>
                        <td>{{ $p->ville->name ?? ''}}</td>
                        <td>{{ $p->pays->name ?? ''}}</td>
                        <td>{{ $p->created_at ?? ''}}</td>
                        <td nowrap="nowrap">
                            <a class="btn btn-sm btn-clean btn-icon mr-2" title="Voir details" href="{{ route('vendeurs.show',$p->id) }}">
                                <i class="flaticon-eye icon-md"></i>
                            </a>
                            @can('commerce-edit')
                                <a class="btn btn-sm btn-clean btn-icon mr-2" title="Modifier details" href="{{ route('vendeurs.edit',$p->id) }}">
                                    <i class='flaticon2-edit icon-md'></i>
                                </a>
                            @endcan
                            @can('commerce-delete')
                                {!! Form::open(['method' => 'DELETE','route' => ['vendeurs.destroy', $p->id],'id'=>'form-suppression'.$p->id,'style'=>'display:inline']) !!}
                                <button class="btn btn-sm btn-clean btn-icon delete-form-row" type="submit" data-val="{{ $p->id }}"><i class='flaticon-delete icon-md'></i></button>
                                {!! Form::close() !!}
                            @endcan
                        </td>
                    </tr>
                @endforeach

                </tbody>
            </table>
            <!--end: Datatable-->
        </div>
    </div>
    <!--end::Card-->

@endsection

@section('end_javascript')
    <script>
    "use strict";
    var KTDatatablesBasicScrollable = function() {

    var initTable1 = function() {
        var table = $('#kt_datatable1');

        // begin first table
        table.DataTable({
            scrollX: true,
            scrollCollapse: true,
        });
    };


    return {

    //main function to initiate the module
    init: function() {
    initTable1();
    },

    };

    }();

    jQuery(document).ready(function() {
    KTDatatablesBasicScrollable.init();
    });
    </script>
@endsection